"""
The 35-team incident-response catalog for the Teams step, organized into
4 tiers -- matches the latest design (new slack design (6)/index.html).
Only Mandatory-tier teams must be staffed to continue; the others are
there to pick from if relevant to the organization.
"""

TIERS = ["Mandatory", "Recommended", "Optional", "External"]

TIER_DESC = {
    "Mandatory": "Every organization must cover these. Not selecting one is flagged as a GAP.",
    "Recommended": "Required when the applicability trigger matches your organization profile.",
    "Optional": "Supporting functions that improve response maturity.",
    "External": "Third parties the organization may rely on (MSSP, IR retainer, counsel, insurer, CERT-In, vendors).",
}

TIER_EMOJI = {"Mandatory": ":red_circle:", "Recommended": ":large_orange_circle:", "Optional": ":large_green_circle:", "External": ":white_circle:"}

ALL_TEAMS = [
    # ── MANDATORY (T01-T06) ──────────────────────────────────────────
    {"id": "T01", "tier": "Mandatory", "name": "Incident Command / IR Management", "type": "Internal",
     "trigger": "Always required for every organization.",
     "purpose": "Owns the incident end to end: declares incidents, sets severity, coordinates all teams and drives decisions until closure.",
     "phases": "All phases", "outsource": "Partially (IR retainer can support, but an internal owner is required)"},
    {"id": "T02", "tier": "Mandatory", "name": "Security Operations Center (Detection & Analysis)", "type": "Internal",
     "trigger": "Always required (can be in-house, hybrid or MSSP-backed).",
     "purpose": "Detects, triages and analyses security events; confirms incidents and determines scope and impact.",
     "phases": "Detection & Analysis; Containment", "outsource": "Yes (MSSP/MDR)"},
    {"id": "T03", "tier": "Mandatory", "name": "IT Operations & Infrastructure (Technical Response)", "type": "Internal",
     "trigger": "Always required.",
     "purpose": "Executes technical containment, eradication and recovery across servers, endpoints, networks and backups.",
     "phases": "Containment; Eradication; Recovery", "outsource": "Partially (managed IT provider)"},
    {"id": "T04", "tier": "Mandatory", "name": "Executive Leadership / Crisis Management", "type": "Internal",
     "trigger": "Always required for strategic decisions and resource approval.",
     "purpose": "Makes business-critical decisions, approves resources and owns board, investor and strategic accountability.",
     "phases": "Preparation; Containment; Post-Incident", "outsource": "No"},
    {"id": "T05", "tier": "Mandatory", "name": "Legal & Regulatory Affairs", "type": "Internal",
     "trigger": "Always required (internal counsel or designated legal advisor).",
     "purpose": "Determines legal and regulatory obligations, preserves privilege, manages notifications and liability.",
     "phases": "Containment; Post-Incident", "outsource": "Partially (external counsel / breach coach)"},
    {"id": "T06", "tier": "Mandatory", "name": "Corporate Communications & PR", "type": "Internal",
     "trigger": "Always required for any incident with internal or external communication impact.",
     "purpose": "Controls internal and external messaging so that communications are accurate, timely, consistent and legally reviewed.",
     "phases": "Containment; Recovery; Post-Incident", "outsource": "Partially (PR agency)"},
    # ── RECOMMENDED (T07-T19) ────────────────────────────────────────
    {"id": "T07", "tier": "Recommended", "name": "Digital Forensics & Incident Response (DFIR)", "type": "Internal",
     "trigger": "Medium/large orgs, regulated sectors, or any org expecting litigation or insurance claims.",
     "purpose": "Collects and analyses evidence in a forensically sound way to establish root cause, timeline and attacker activity.",
     "phases": "Detection & Analysis; Eradication; Post-Incident", "outsource": "Yes (IR retainer firm)"},
    {"id": "T08", "tier": "Recommended", "name": "Threat Intelligence (CTI)", "type": "Internal",
     "trigger": "Targeted sectors (BFSI, government, healthcare, defence, tech) or mature security programs.",
     "purpose": "Provides context on threat actors, TTPs and IOCs to guide detection, scoping and prioritization.",
     "phases": "Preparation; Detection & Analysis", "outsource": "Yes (threat intel feeds / vendors)"},
    {"id": "T09", "tier": "Recommended", "name": "Privacy / Data Protection Office", "type": "Internal",
     "trigger": "Any org processing personal data; mandatory for Significant Data Fiduciaries under DPDP.",
     "purpose": "Assesses personal-data impact and runs breach notifications to data protection authorities and individuals.",
     "phases": "Detection & Analysis; Containment; Post-Incident", "outsource": "Partially (external DPO service)"},
    {"id": "T10", "tier": "Recommended", "name": "Human Resources", "type": "Internal",
     "trigger": "Insider threats, employee-data incidents, or orgs with unionized / large workforces.",
     "purpose": "Handles personnel aspects: insider investigations, disciplinary action, staff communications and welfare.",
     "phases": "Containment; Post-Incident", "outsource": "No"},
    {"id": "T11", "tier": "Recommended", "name": "Business Continuity & Disaster Recovery", "type": "Internal",
     "trigger": "Orgs with critical services, uptime SLAs or regulatory resilience requirements (BFSI, healthcare, CII).",
     "purpose": "Keeps the business running during disruption and restores services in priority order.",
     "phases": "Preparation; Recovery", "outsource": "Partially (managed IT provider)"},
    {"id": "T12", "tier": "Recommended", "name": "Application Security & Engineering (DevOps/SRE)", "type": "Internal",
     "trigger": "Orgs that build software, run SaaS products, websites or customer-facing APIs.",
     "purpose": "Investigates and fixes application-layer compromise, rotates secrets and secures the software supply chain.",
     "phases": "Detection & Analysis; Eradication; Recovery", "outsource": "No"},
    {"id": "T13", "tier": "Recommended", "name": "Cloud Security", "type": "Internal",
     "trigger": "Orgs with significant AWS / Azure / GCP / SaaS footprint.",
     "purpose": "Investigates and contains cloud-control-plane and workload compromise; fixes misconfigurations.",
     "phases": "Detection & Analysis; Containment; Eradication", "outsource": "Yes (cloud MDR)"},
    {"id": "T14", "tier": "Recommended", "name": "Network Security", "type": "Internal",
     "trigger": "Orgs with on-prem networks, multiple sites, or perimeter security appliances.",
     "purpose": "Manages firewalls, segmentation, VPN, DNS and traffic controls used to contain and monitor attacks.",
     "phases": "Containment; Eradication", "outsource": "No"},
    {"id": "T15", "tier": "Recommended", "name": "Identity & Access Management (IAM)", "type": "Internal",
     "trigger": "Recommended for all orgs; critical where SSO/AD/Entra ID or privileged access is central.",
     "purpose": "Controls accounts, credentials, MFA and privileged access to cut off attacker access quickly.",
     "phases": "Containment; Eradication", "outsource": "No"},
    {"id": "T16", "tier": "Recommended", "name": "OT / ICS Security", "type": "Internal",
     "trigger": "Manufacturing, energy, utilities, oil & gas, pharma, transport or any org with industrial control systems.",
     "purpose": "Protects operational technology while keeping human safety and physical processes intact.",
     "phases": "Containment; Eradication", "outsource": "Partially (OT security specialists)"},
    {"id": "T17", "tier": "Recommended", "name": "Vulnerability Management", "type": "Internal",
     "trigger": "Recommended for all orgs; essential for internet-facing assets.",
     "purpose": "Identifies exposed and exploited vulnerabilities and drives emergency patching and verification.",
     "phases": "Preparation; Eradication", "outsource": "Yes"},
    {"id": "T18", "tier": "Recommended", "name": "IT Service Desk / Help Desk", "type": "Internal",
     "trigger": "Recommended for all orgs with an internal help desk.",
     "purpose": "First point of contact for users; spots and escalates incidents and executes user-level response actions.",
     "phases": "Detection & Analysis; Recovery", "outsource": "No"},
    {"id": "T19", "tier": "Recommended", "name": "Business Unit / Process Owners", "type": "Internal",
     "trigger": "Recommended for all orgs; required to make business-impact decisions for affected systems.",
     "purpose": "Represents affected business functions: impact assessment, workarounds and recovery prioritization.",
     "phases": "Containment; Recovery", "outsource": "No"},
    # ── OPTIONAL (T20-T27) ───────────────────────────────────────────
    {"id": "T20", "tier": "Optional", "name": "Risk Management & Cyber Insurance", "type": "Internal",
     "trigger": "Orgs with a formal ERM function or cyber insurance policy.",
     "purpose": "Manages enterprise risk impact, insurer notification and claim requirements.",
     "phases": "Preparation; Post-Incident", "outsource": "No"},
    {"id": "T21", "tier": "Optional", "name": "Finance & Treasury", "type": "Internal",
     "trigger": "Orgs exposed to payment fraud, extortion or with emergency spend needs.",
     "purpose": "Approves emergency spending, stops fraudulent payments and handles financial aspects of extortion.",
     "phases": "Containment; Recovery", "outsource": "No"},
    {"id": "T22", "tier": "Optional", "name": "Customer Support / Customer Success", "type": "Internal",
     "trigger": "B2C or B2B orgs with customer-facing support teams.",
     "purpose": "Handles inbound customer queries using approved scripts and escalates customer-reported issues.",
     "phases": "Recovery; Post-Incident", "outsource": "No"},
    {"id": "T23", "tier": "Optional", "name": "Physical Security & Facilities", "type": "Internal",
     "trigger": "Orgs with offices, data centres, plants or high-value physical assets.",
     "purpose": "Controls physical access and secures facilities, hardware and evidence.",
     "phases": "Containment; Eradication", "outsource": "No"},
    {"id": "T24", "tier": "Optional", "name": "Third-Party / Vendor Risk Management", "type": "Internal",
     "trigger": "Orgs relying heavily on suppliers, SaaS, outsourced IT or processors.",
     "purpose": "Coordinates with vendors during incidents and enforces contractual security and notification clauses.",
     "phases": "Preparation; Detection & Analysis; Post-Incident", "outsource": "No"},
    {"id": "T25", "tier": "Optional", "name": "Governance, Risk & Compliance (GRC)", "type": "Internal",
     "trigger": "Orgs with certifications (ISO 27001, SOC 2, PCI DSS) or regulatory audits.",
     "purpose": "Maintains IR policy, maps incidents to control frameworks and manages audit evidence.",
     "phases": "Post-Incident", "outsource": "No"},
    {"id": "T26", "tier": "Optional", "name": "Internal Audit", "type": "Internal",
     "trigger": "Listed companies, BFSI and orgs with an internal audit function.",
     "purpose": "Independently reviews IR effectiveness and follows up on remediation actions.",
     "phases": "Post-Incident", "outsource": "No"},
    {"id": "T27", "tier": "Optional", "name": "Security Awareness & Training", "type": "Internal",
     "trigger": "Recommended for all orgs; especially where phishing/BEC is a top threat.",
     "purpose": "Turns incident lessons into user awareness, targeted training and phishing simulations.",
     "phases": "Post-Incident", "outsource": "No"},
    # ── EXTERNAL (T28-T35) ───────────────────────────────────────────
    {"id": "T28", "tier": "External", "name": "MSSP / MDR Provider", "type": "External",
     "trigger": "Orgs that outsource monitoring, detection or response.",
     "purpose": "Provides 24x7 monitoring, detection and first-response actions under contract.",
     "phases": "Detection & Analysis; Containment", "outsource": "N/A (is external)"},
    {"id": "T29", "tier": "External", "name": "External IR Retainer / DFIR Firm", "type": "External",
     "trigger": "Orgs without in-house DFIR, or for major incidents; often required by cyber insurers.",
     "purpose": "Provides surge incident response, forensics, threat hunting and recovery expertise.",
     "phases": "All phases", "outsource": "N/A (is external)"},
    {"id": "T30", "tier": "External", "name": "External Legal Counsel / Breach Coach", "type": "External",
     "trigger": "Significant incidents, cross-border breaches, litigation risk or where required by insurer.",
     "purpose": "Directs the investigation under privilege and advises on notifications, liability and regulator engagement.",
     "phases": "Containment; Post-Incident", "outsource": "N/A (is external)"},
    {"id": "T31", "tier": "External", "name": "Cyber Insurance Carrier", "type": "External",
     "trigger": "Orgs with a cyber insurance policy.",
     "purpose": "Receives notice of claim, approves panel vendors and covers eligible response costs.",
     "phases": "Post-Incident", "outsource": "N/A (is external)"},
    {"id": "T32", "tier": "External", "name": "External PR / Crisis Communications Agency", "type": "External",
     "trigger": "High-profile brands, listed companies or incidents with media exposure.",
     "purpose": "Supports media strategy, statements and reputation management.",
     "phases": "Containment; Recovery; Post-Incident", "outsource": "N/A (is external)"},
    {"id": "T33", "tier": "External", "name": "Law Enforcement & Government CERT Liaison", "type": "External",
     "trigger": "Criminal activity (extortion, fraud, data theft) or mandatory government reporting.",
     "purpose": "Receives mandatory reports, provides threat info and may support investigations.",
     "phases": "Detection & Analysis; Post-Incident", "outsource": "N/A (is external)"},
    {"id": "T34", "tier": "External", "name": "Critical Technology Vendors (Cloud, SaaS, ISP, OEM)", "type": "External",
     "trigger": "All orgs relying on key technology providers.",
     "purpose": "Provides vendor-side logs, patches, takedowns, DDoS scrubbing and escalated support.",
     "phases": "Detection & Analysis; Containment; Recovery", "outsource": "N/A (is external)"},
    {"id": "T35", "tier": "External", "name": "Ransomware / Extortion Negotiation Specialist", "type": "External",
     "trigger": "Ransomware or data-extortion incidents; usually engaged via insurer or IR firm.",
     "purpose": "Communicates with threat actors under legal direction, validates claims and buys time for response.",
     "phases": "Containment", "outsource": "N/A (is external)"},
]

MANDATORY_TEAM_IDS = [t["id"] for t in ALL_TEAMS if t["tier"] == "Mandatory"]


def teams_in_tier(tier: str) -> list:
    return [t for t in ALL_TEAMS if t["tier"] == tier]


def find_team(team_id: str) -> dict | None:
    return next((t for t in ALL_TEAMS if t["id"] == team_id), None)


# Real per-team roles from sir's "IR Team Catalog TestMyPlan - For Dev.xlsx"
# (Roles sheet) -- each team has its OWN specific roles, not the same
# generic 8 roles reused everywhere. "priority" here is Mandatory /
# Recommended / Optional *within that team* (independent of the team's own
# tier above) -- e.g. T01 is a Mandatory team, but within it "Incident
# Coordinator / Project Manager" is only Recommended.
ROLE_CATALOG_BY_TEAM = {
    "T01": [{"role_id": "R001", "role": "Incident Commander (IR Lead)", "priority": "Mandatory"}, {"role_id": "R002", "role": "Deputy Incident Commander", "priority": "Mandatory"}, {"role_id": "R003", "role": "Incident Coordinator / Project Manager", "priority": "Recommended"}, {"role_id": "R004", "role": "Scribe / Documentation Lead", "priority": "Mandatory"}],
    "T02": [{"role_id": "R005", "role": "SOC Manager", "priority": "Mandatory"}, {"role_id": "R006", "role": "SOC Analyst - Tier 1 (Triage)", "priority": "Mandatory"}, {"role_id": "R007", "role": "SOC Analyst - Tier 2 (Investigation)", "priority": "Mandatory"}, {"role_id": "R008", "role": "SOC Analyst - Tier 3 / Threat Hunter", "priority": "Recommended"}, {"role_id": "R009", "role": "Detection / SIEM Engineer", "priority": "Recommended"}],
    "T03": [{"role_id": "R010", "role": "IT Operations Lead / Infrastructure Manager", "priority": "Mandatory"}, {"role_id": "R011", "role": "System Administrator (Windows/Linux)", "priority": "Mandatory"}, {"role_id": "R012", "role": "Network Administrator", "priority": "Mandatory"}, {"role_id": "R013", "role": "Backup & Recovery Administrator", "priority": "Mandatory"}, {"role_id": "R014", "role": "Endpoint / Desktop Administrator", "priority": "Recommended"}, {"role_id": "R015", "role": "Database Administrator", "priority": "Recommended"}],
    "T04": [{"role_id": "R016", "role": "Executive Sponsor (CEO / MD)", "priority": "Mandatory"}, {"role_id": "R017", "role": "Chief Information Security Officer (CISO)", "priority": "Mandatory"}, {"role_id": "R018", "role": "Chief Information / Technology Officer (CIO/CTO)", "priority": "Mandatory"}, {"role_id": "R019", "role": "Chief Operating Officer (COO)", "priority": "Recommended"}, {"role_id": "R020", "role": "Board / Audit or Risk Committee Liaison", "priority": "Optional"}],
    "T05": [{"role_id": "R021", "role": "General Counsel / Legal Lead", "priority": "Mandatory"}, {"role_id": "R022", "role": "Regulatory Compliance Officer", "priority": "Mandatory"}, {"role_id": "R023", "role": "Contracts & Commercial Counsel", "priority": "Recommended"}, {"role_id": "R024", "role": "Designated CERT-In Point of Contact", "priority": "Mandatory"}],
    "T06": [{"role_id": "R025", "role": "Communications Lead", "priority": "Mandatory"}, {"role_id": "R026", "role": "Media Spokesperson", "priority": "Mandatory"}, {"role_id": "R027", "role": "Internal Communications Manager", "priority": "Recommended"}, {"role_id": "R028", "role": "Customer & Partner Communications Manager", "priority": "Recommended"}, {"role_id": "R029", "role": "Social Media Manager", "priority": "Optional"}],
    "T07": [{"role_id": "R030", "role": "Forensics Lead", "priority": "Mandatory"}, {"role_id": "R031", "role": "Digital Forensic Analyst", "priority": "Mandatory"}, {"role_id": "R032", "role": "Malware Analyst / Reverse Engineer", "priority": "Recommended"}, {"role_id": "R033", "role": "Evidence Custodian", "priority": "Recommended"}],
    "T08": [{"role_id": "R034", "role": "Threat Intelligence Lead", "priority": "Mandatory"}, {"role_id": "R035", "role": "Threat Intelligence Analyst", "priority": "Mandatory"}],
    "T09": [{"role_id": "R036", "role": "Data Protection Officer (DPO) / Privacy Lead", "priority": "Mandatory"}, {"role_id": "R037", "role": "Privacy Analyst", "priority": "Recommended"}],
    "T10": [{"role_id": "R038", "role": "HR Business Partner / HR Lead", "priority": "Mandatory"}, {"role_id": "R039", "role": "Employee Relations / Investigations Specialist", "priority": "Optional"}],
    "T11": [{"role_id": "R040", "role": "Business Continuity Manager", "priority": "Mandatory"}, {"role_id": "R041", "role": "Disaster Recovery Coordinator", "priority": "Mandatory"}],
    "T12": [{"role_id": "R042", "role": "Application Security Lead", "priority": "Mandatory"}, {"role_id": "R043", "role": "DevOps / SRE Engineer", "priority": "Mandatory"}, {"role_id": "R044", "role": "Lead Developer / Engineering Manager", "priority": "Recommended"}],
    "T13": [{"role_id": "R045", "role": "Cloud Security Engineer", "priority": "Mandatory"}, {"role_id": "R046", "role": "Cloud Architect / Platform Owner", "priority": "Recommended"}],
    "T14": [{"role_id": "R047", "role": "Network Security Engineer", "priority": "Mandatory"}, {"role_id": "R048", "role": "Firewall / Perimeter Administrator", "priority": "Recommended"}],
    "T15": [{"role_id": "R049", "role": "IAM Lead / Identity Administrator", "priority": "Mandatory"}, {"role_id": "R050", "role": "Privileged Access Management (PAM) Administrator", "priority": "Recommended"}],
    "T16": [{"role_id": "R051", "role": "OT Security Lead", "priority": "Mandatory"}, {"role_id": "R052", "role": "Plant / Process Control Engineer", "priority": "Mandatory"}, {"role_id": "R053", "role": "Health, Safety & Environment (HSE) Officer", "priority": "Recommended"}],
    "T17": [{"role_id": "R054", "role": "Vulnerability Management Lead", "priority": "Mandatory"}, {"role_id": "R055", "role": "Penetration Tester / Red Team", "priority": "Optional"}],
    "T18": [{"role_id": "R056", "role": "Service Desk Lead", "priority": "Mandatory"}, {"role_id": "R057", "role": "Service Desk Analyst", "priority": "Recommended"}],
    "T19": [{"role_id": "R058", "role": "Business Unit Representative", "priority": "Mandatory"}, {"role_id": "R059", "role": "Application / System Owner", "priority": "Mandatory"}],
    "T20": [{"role_id": "R060", "role": "Enterprise Risk Manager", "priority": "Mandatory"}, {"role_id": "R061", "role": "Cyber Insurance Liaison", "priority": "Mandatory"}],
    "T21": [{"role_id": "R062", "role": "Finance Controller / CFO Delegate", "priority": "Mandatory"}, {"role_id": "R063", "role": "Treasury / Payments Lead", "priority": "Recommended"}],
    "T22": [{"role_id": "R064", "role": "Customer Support Manager", "priority": "Mandatory"}, {"role_id": "R065", "role": "Customer Support Agent", "priority": "Optional"}],
    "T23": [{"role_id": "R066", "role": "Physical Security Manager", "priority": "Mandatory"}, {"role_id": "R067", "role": "Facilities / Data Centre Manager", "priority": "Recommended"}],
    "T24": [{"role_id": "R068", "role": "Vendor / Third-Party Risk Manager", "priority": "Mandatory"}],
    "T25": [{"role_id": "R069", "role": "GRC Manager", "priority": "Mandatory"}],
    "T26": [{"role_id": "R070", "role": "Internal Auditor (IT/Cyber)", "priority": "Mandatory"}],
    "T27": [{"role_id": "R071", "role": "Security Awareness Lead", "priority": "Mandatory"}],
    "T28": [{"role_id": "R072", "role": "MSSP / MDR Account Manager", "priority": "Mandatory"}, {"role_id": "R073", "role": "MSSP / MDR Incident Handler", "priority": "Mandatory"}],
    "T29": [{"role_id": "R074", "role": "Retainer Engagement Lead", "priority": "Mandatory"}, {"role_id": "R075", "role": "External Forensic / IR Consultant", "priority": "Recommended"}],
    "T30": [{"role_id": "R076", "role": "Breach Coach / External Privacy Counsel", "priority": "Mandatory"}],
    "T31": [{"role_id": "R077", "role": "Insurance Claims Handler", "priority": "Mandatory"}],
    "T32": [{"role_id": "R078", "role": "Crisis Communications Consultant", "priority": "Mandatory"}],
    "T33": [{"role_id": "R079", "role": "Government CERT Contact (CERT-In / NCIIPC / National CERT)", "priority": "Mandatory"}, {"role_id": "R080", "role": "Law Enforcement Contact (Cyber Cell / I4C / FBI)", "priority": "Recommended"}],
    "T34": [{"role_id": "R081", "role": "Cloud / SaaS Provider Support Contact", "priority": "Mandatory"}, {"role_id": "R082", "role": "ISP / DDoS Mitigation Provider Contact", "priority": "Recommended"}, {"role_id": "R083", "role": "Security Product OEM Support", "priority": "Optional"}],
    "T35": [{"role_id": "R084", "role": "Ransomware Negotiator", "priority": "Mandatory"}],
}


def roles_for_team(team_id: str) -> list:
    """Real roles for one team, or [] if this team isn't in the catalog yet."""
    return ROLE_CATALOG_BY_TEAM.get(team_id, [])


# Real responsibility/action/phase per (team_id, role) -- also from sir's
# spreadsheet (Roles sheet's "Role Responsibilities"/"Key IR Activity"/
# "IR Phase" columns, one representative activity per role). Restores
# the auto-mapping that broke when the 8 generic roles were replaced with
# these 84 real per-team ones -- picking a role now maps its actual
# responsibility again instead of nothing.
ROLE_RESP_BY_TEAM_ROLE = {
    ("T01", "Deputy Incident Commander"): {"text": "Backs up the Incident Commander and takes over during shift changes or unavailability.", "action": "Execute", "detail": "Run parallel workstreams", "phase": "Containment"},
    ("T01", "Incident Commander (IR Lead)"): {"text": "Single point of authority during an incident; owns decisions, priorities and cross-team coordination.", "action": "Decide", "detail": "Declare incident and severity", "phase": "Identification"},
    ("T01", "Incident Coordinator / Project Manager"): {"text": "Manages logistics, schedules and task tracking so responders can focus on technical work.", "action": "Execute", "detail": "Maintain task tracker", "phase": "Containment"},
    ("T01", "Scribe / Documentation Lead"): {"text": "Maintains the official incident record for legal, regulatory and lessons-learned purposes.", "action": "Execute", "detail": "Keep time-stamped incident log", "phase": "Identification"},
    ("T02", "Detection / SIEM Engineer"): {"text": "Maintains the logging, SIEM and detection-content pipeline.", "action": "Execute", "detail": "Onboard missing log sources during incidents", "phase": "Identification"},
    ("T02", "SOC Analyst - Tier 1 (Triage)"): {"text": "Monitors alerts and performs initial triage and validation.", "action": "Execute", "detail": "Monitor SIEM/EDR queues", "phase": "Identification"},
    ("T02", "SOC Analyst - Tier 2 (Investigation)"): {"text": "Performs deeper investigation to determine scope, impact and attack path.", "action": "Execute", "detail": "Correlate logs across sources", "phase": "Identification"},
    ("T02", "SOC Analyst - Tier 3 / Threat Hunter"): {"text": "Proactively hunts for undetected attacker activity and handles complex investigations.", "action": "Execute", "detail": "Hypothesis-driven hunts", "phase": "Identification"},
    ("T02", "SOC Manager"): {"text": "Leads the SOC and ensures 24x7 detection, triage and escalation coverage.", "action": "Execute", "detail": "Staff shifts", "phase": "Identification"},
    ("T03", "Backup & Recovery Administrator"): {"text": "Ensures clean, restorable backups and executes data restoration.", "action": "Verify", "detail": "Verify backup integrity and immutability", "phase": "Identification"},
    ("T03", "Database Administrator"): {"text": "Protects and investigates databases holding critical or personal data.", "action": "Verify", "detail": "Review DB audit logs for exfiltration", "phase": "Identification"},
    ("T03", "Endpoint / Desktop Administrator"): {"text": "Handles user device containment, reimaging and software deployment.", "action": "Execute", "detail": "Wipe lost devices", "phase": "Containment"},
    ("T03", "IT Operations Lead / Infrastructure Manager"): {"text": "Coordinates all technical response actions on infrastructure.", "action": "Execute", "detail": "Assign technical tasks", "phase": "Containment"},
    ("T03", "Network Administrator"): {"text": "Executes network-level containment and restoration.", "action": "Execute", "detail": "Capture traffic", "phase": "Identification"},
    ("T03", "System Administrator (Windows/Linux)"): {"text": "Executes containment, eradication and rebuild actions on servers and endpoints.", "action": "Execute", "detail": "Isolate or shut down hosts", "phase": "Containment"},
    ("T04", "Board / Audit or Risk Committee Liaison"): {"text": "Keeps the board informed and meets governance oversight obligations.", "action": "Execute", "detail": "Support materiality determination for listed entities", "phase": "Identification"},
    ("T04", "Chief Information / Technology Officer (CIO/CTO)"): {"text": "Owns IT systems and technology recovery decisions.", "action": "Approve", "detail": "Approve system shutdowns and recovery priorities", "phase": "Containment"},
    ("T04", "Chief Information Security Officer (CISO)"): {"text": "Senior security leader bridging technical response and executive decision-making.", "action": "Notify", "detail": "Brief executives and board", "phase": "Containment"},
    ("T04", "Chief Operating Officer (COO)"): {"text": "Owns operational continuity and customer/service impact.", "action": "Decide", "detail": "Decide on manual operations and service degradation", "phase": "Containment"},
    ("T04", "Executive Sponsor (CEO / MD)"): {"text": "Ultimate business accountability and authority for major decisions.", "action": "Approve", "detail": "Approve business shutdown/continuity decisions", "phase": "Containment"},
    ("T05", "Contracts & Commercial Counsel"): {"text": "Reviews contractual obligations with customers, vendors and insurers.", "action": "Execute", "detail": "Identify contractual notification deadlines", "phase": "Identification"},
    ("T05", "Designated CERT-In Point of Contact"): {"text": "Named liaison required under CERT-In Directions 2022 for communication with CERT-In.", "action": "Execute", "detail": "Submit incident reports to CERT-In within 6 hours", "phase": "Identification"},
    ("T05", "General Counsel / Legal Lead"): {"text": "Leads legal strategy and protects the organization's legal position.", "action": "Execute", "detail": "Establish legal privilege", "phase": "Identification"},
    ("T05", "Regulatory Compliance Officer"): {"text": "Tracks and fulfils mandatory regulatory reporting obligations.", "action": "Execute", "detail": "Identify applicable regulators", "phase": "Identification"},
    ("T06", "Communications Lead"): {"text": "Owns the communication strategy for the incident.", "action": "Execute", "detail": "Build comms plan", "phase": "Containment"},
    ("T06", "Customer & Partner Communications Manager"): {"text": "Manages notifications to customers, partners and affected individuals.", "action": "Execute", "detail": "Draft customer notices and FAQs", "phase": "Containment"},
    ("T06", "Internal Communications Manager"): {"text": "Keeps employees informed and prevents leaks or rumours.", "action": "Execute", "detail": "Send staff updates and do/don't guidance", "phase": "Containment"},
    ("T06", "Media Spokesperson"): {"text": "Authorized public voice of the organization.", "action": "Execute", "detail": "Deliver media statements", "phase": "Containment"},
    ("T06", "Social Media Manager"): {"text": "Monitors and responds on social channels.", "action": "Execute", "detail": "Monitor social chatter and leak sites mentions", "phase": "Identification"},
    ("T07", "Digital Forensic Analyst"): {"text": "Performs disk, memory, log and cloud forensic analysis.", "action": "Execute", "detail": "Acquire disk/memory images", "phase": "Identification"},
    ("T07", "Evidence Custodian"): {"text": "Maintains custody, storage and integrity of evidence.", "action": "Execute", "detail": "Log chain-of-custody forms", "phase": "Identification"},
    ("T07", "Forensics Lead"): {"text": "Leads forensic investigation and ensures evidentiary integrity.", "action": "Execute", "detail": "Define forensic scope", "phase": "Identification"},
    ("T07", "Malware Analyst / Reverse Engineer"): {"text": "Analyses malicious code to understand capability and extract IOCs.", "action": "Execute", "detail": "Static/dynamic malware analysis", "phase": "Identification"},
    ("T08", "Threat Intelligence Analyst"): {"text": "Researches and enriches incident indicators.", "action": "Execute", "detail": "Enrich IOCs", "phase": "Identification"},
    ("T08", "Threat Intelligence Lead"): {"text": "Directs intelligence support to the incident.", "action": "Execute", "detail": "Set intel requirements", "phase": "Identification"},
    ("T09", "Data Protection Officer (DPO) / Privacy Lead"): {"text": "Leads personal-data breach assessment and notification.", "action": "Execute", "detail": "Assess whether personal data is affected", "phase": "Identification"},
    ("T09", "Privacy Analyst"): {"text": "Supports impact assessment and records keeping.", "action": "Execute", "detail": "Identify data categories and counts affected", "phase": "Identification"},
    ("T10", "Employee Relations / Investigations Specialist"): {"text": "Conducts HR investigations in coordination with Legal and Security.", "action": "Execute", "detail": "Interview staff", "phase": "Identification"},
    ("T10", "HR Business Partner / HR Lead"): {"text": "Leads people-related response actions.", "action": "Execute", "detail": "Coordinate insider investigations", "phase": "Identification"},
    ("T11", "Business Continuity Manager"): {"text": "Activates and manages business continuity plans.", "action": "Execute", "detail": "Activate BCP", "phase": "Containment"},
    ("T11", "Disaster Recovery Coordinator"): {"text": "Executes technical disaster recovery plans.", "action": "Execute", "detail": "Fail over to DR site", "phase": "Recovery"},
    ("T12", "Application Security Lead"): {"text": "Leads application-layer investigation and remediation.", "action": "Execute", "detail": "Analyse app/WAF logs", "phase": "Identification"},
    ("T12", "DevOps / SRE Engineer"): {"text": "Secures and restores CI/CD pipelines and production environments.", "action": "Verify", "detail": "Review deployment logs for tampering", "phase": "Identification"},
    ("T12", "Lead Developer / Engineering Manager"): {"text": "Provides code-level knowledge and fix implementation.", "action": "Verify", "detail": "Review commits", "phase": "Identification"},
    ("T13", "Cloud Architect / Platform Owner"): {"text": "Owns cloud environment design and approves structural changes.", "action": "Approve", "detail": "Approve account/tenant isolation", "phase": "Containment"},
    ("T13", "Cloud Security Engineer"): {"text": "Investigates and contains cloud compromise.", "action": "Verify", "detail": "Review CloudTrail/Azure Activity/GCP audit logs", "phase": "Identification"},
    ("T14", "Firewall / Perimeter Administrator"): {"text": "Executes emergency perimeter changes.", "action": "Execute", "detail": "Block attacker infrastructure", "phase": "Containment"},
    ("T14", "Network Security Engineer"): {"text": "Manages security controls on the network perimeter and internal segments.", "action": "Execute", "detail": "Analyse NetFlow/PCAP", "phase": "Identification"},
    ("T15", "IAM Lead / Identity Administrator"): {"text": "Controls identity systems during response.", "action": "Verify", "detail": "Review sign-in logs", "phase": "Identification"},
    ("T15", "Privileged Access Management (PAM) Administrator"): {"text": "Secures privileged and service accounts.", "action": "Verify", "detail": "Audit admin group changes", "phase": "Identification"},
    ("T16", "Health, Safety & Environment (HSE) Officer"): {"text": "Ensures human and environmental safety during OT incidents.", "action": "Execute", "detail": "Assess safety risk", "phase": "Identification"},
    ("T16", "OT Security Lead"): {"text": "Leads OT incident response while prioritizing safety.", "action": "Execute", "detail": "Assess impact on control systems", "phase": "Identification"},
    ("T16", "Plant / Process Control Engineer"): {"text": "Operates and restores industrial processes safely.", "action": "Verify", "detail": "Validate PLC/HMI integrity", "phase": "Identification"},
    ("T17", "Penetration Tester / Red Team"): {"text": "Validates that exploited paths are closed after remediation.", "action": "Execute", "detail": "Retest exploited vulnerabilities", "phase": "Post-Incident Activity"},
    ("T17", "Vulnerability Management Lead"): {"text": "Prioritizes and tracks remediation of exploited and critical vulnerabilities.", "action": "Execute", "detail": "Identify exposed assets", "phase": "Identification"},
    ("T18", "Service Desk Analyst"): {"text": "Handles user calls and executes basic response steps.", "action": "Execute", "detail": "Log incident reports", "phase": "Identification"},
    ("T18", "Service Desk Lead"): {"text": "Manages user-facing support and first-line incident intake.", "action": "Execute", "detail": "Escalate suspicious user reports", "phase": "Identification"},
    ("T19", "Application / System Owner"): {"text": "Accountable owner of affected business applications.", "action": "Approve", "detail": "Approve downtime and changes", "phase": "Containment"},
    ("T19", "Business Unit Representative"): {"text": "Represents affected business functions in decision-making.", "action": "Execute", "detail": "Assess operational and customer impact", "phase": "Identification"},
    ("T20", "Cyber Insurance Liaison"): {"text": "Manages communication with the insurer to protect coverage.", "action": "Notify", "detail": "Notify insurer within policy timelines", "phase": "Containment"},
    ("T20", "Enterprise Risk Manager"): {"text": "Assesses enterprise risk impact of the incident.", "action": "Execute", "detail": "Quantify financial and operational impact", "phase": "Post-Incident Activity"},
    ("T21", "Finance Controller / CFO Delegate"): {"text": "Authorizes emergency spend and financial response actions.", "action": "Approve", "detail": "Approve emergency procurement", "phase": "Containment"},
    ("T21", "Treasury / Payments Lead"): {"text": "Protects payment flows against fraud.", "action": "Execute", "detail": "Halt or recall fraudulent transfers (BEC)", "phase": "Containment"},
    ("T22", "Customer Support Agent"): {"text": "Handles individual customer interactions.", "action": "Execute", "detail": "Route suspected fraud reports", "phase": "Identification"},
    ("T22", "Customer Support Manager"): {"text": "Leads customer-facing support during incidents.", "action": "Execute", "detail": "Escalate customer-reported anomalies to SOC", "phase": "Identification"},
    ("T23", "Facilities / Data Centre Manager"): {"text": "Supports physical infrastructure actions.", "action": "Provide evidence", "detail": "Provide DC access for responders", "phase": "Containment"},
    ("T23", "Physical Security Manager"): {"text": "Controls physical access and site security.", "action": "Verify", "detail": "Review CCTV/badge logs", "phase": "Identification"},
    ("T24", "Vendor / Third-Party Risk Manager"): {"text": "Coordinates vendor involvement and contractual obligations.", "action": "Execute", "detail": "Contact affected vendors", "phase": "Identification"},
    ("T25", "GRC Manager"): {"text": "Maintains the IR policy framework and compliance evidence.", "action": "Execute", "detail": "Map incident to controls (ISO 27001, SOC 2, PCI DSS)", "phase": "Post-Incident Activity"},
    ("T26", "Internal Auditor (IT/Cyber)"): {"text": "Provides independent assurance over IR performance.", "action": "Verify", "detail": "Review incident handling against policy", "phase": "Post-Incident Activity"},
    ("T27", "Security Awareness Lead"): {"text": "Converts incidents into awareness and training improvements.", "action": "Execute", "detail": "Issue user alerts about active campaigns", "phase": "Containment"},
    ("T28", "MSSP / MDR Account Manager"): {"text": "Primary commercial and escalation contact at the provider.", "action": "Verify", "detail": "Confirm contractual scope and SLAs", "phase": "Identification"},
    ("T28", "MSSP / MDR Incident Handler"): {"text": "Provider analyst executing monitoring and response actions.", "action": "Execute", "detail": "Escalate detections to client", "phase": "Identification"},
    ("T29", "External Forensic / IR Consultant"): {"text": "Hands-on external responder.", "action": "Execute", "detail": "Deploy forensic tooling", "phase": "Identification"},
    ("T29", "Retainer Engagement Lead"): {"text": "Leads the external IR firm's engagement.", "action": "Execute", "detail": "Mobilize responders within retainer SLA", "phase": "Identification"},
    ("T30", "Breach Coach / External Privacy Counsel"): {"text": "External legal advisor directing the response under privilege.", "action": "Execute", "detail": "Engage forensic firm via counsel", "phase": "Identification"},
    ("T31", "Insurance Claims Handler"): {"text": "Insurer's contact for the claim.", "action": "Execute", "detail": "Acknowledge notice", "phase": "Containment"},
    ("T32", "Crisis Communications Consultant"): {"text": "External PR advisor for high-exposure incidents.", "action": "Execute", "detail": "Develop media strategy", "phase": "Containment"},
    ("T33", "Government CERT Contact (CERT-In / NCIIPC / National CERT)"): {"text": "Receives mandatory reports and provides national-level support and advisories.", "action": "Execute", "detail": "Receive incident reports", "phase": "Identification"},
    ("T33", "Law Enforcement Contact (Cyber Cell / I4C / FBI)"): {"text": "Handles criminal investigation and complaints.", "action": "Execute", "detail": "Receive FIR/complaint", "phase": "Containment"},
    ("T34", "Cloud / SaaS Provider Support Contact"): {"text": "Vendor escalation path for platform-side investigation and containment.", "action": "Provide evidence", "detail": "Provide platform logs", "phase": "Identification"},
    ("T34", "ISP / DDoS Mitigation Provider Contact"): {"text": "Network-level mitigation provider.", "action": "Provide evidence", "detail": "Provide traffic analysis", "phase": "Identification"},
    ("T34", "Security Product OEM Support"): {"text": "Vendor support for security tooling (EDR, firewall, SIEM).", "action": "Execute", "detail": "Troubleshoot tooling during incident", "phase": "Containment"},
    ("T35", "Ransomware Negotiator"): {"text": "Specialist handling threat-actor communication under legal direction.", "action": "Verify", "detail": "Verify proof of data/decryption claims", "phase": "Containment"},
}


def default_responsibility_for(team_id: str, role: str) -> dict | None:
    """Real auto-mapped responsibility for a role within a specific team."""
    return ROLE_RESP_BY_TEAM_ROLE.get((team_id, role))
