"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-_jyvbc7_53_p*&6*6w!q$j8h0j63v0w8(kk8uwdbslk19@g_b&",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "accounts",
    "commands",
    "home_tab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Frontend origin(s) allowed to call this API (Vite dev server, prod domain, etc.)
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173",
    cast=Csv(),
)
CORS_ALLOW_CREDENTIALS = True

# Where to send the browser after a successful Slack/Teams login
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")
FRONTEND_LOGIN_SUCCESS_PATH = config("FRONTEND_LOGIN_SUCCESS_PATH", default="/dashboard")
FRONTEND_LOGIN_ERROR_PATH = config("FRONTEND_LOGIN_ERROR_PATH", default="/login")

# Public base URL of this backend (used to build OAuth redirect_uri values)
BACKEND_URL = config("BACKEND_URL", default="http://localhost:8000")

# --- Slack OAuth ---
SLACK_CLIENT_ID = config("SLACK_CLIENT_ID", default="")
SLACK_CLIENT_SECRET = config("SLACK_CLIENT_SECRET", default="")
SLACK_REDIRECT_URI = config(
    "SLACK_REDIRECT_URI", default=f"{BACKEND_URL}/api/auth/slack/callback/"
)
SLACK_SCOPES = config("SLACK_SCOPES", default="openid,email,profile")
# Used to verify that a slash-command request really came from Slack.
# Find it in api.slack.com/apps -> your app -> Basic Information -> Signing Secret.
SLACK_SIGNING_SECRET = config("SLACK_SIGNING_SECRET", default="")

# Bot token used to actively call Slack's API (e.g. publish the Home tab).
# Find it in api.slack.com/apps -> your app -> OAuth & Permissions ->
# "Bot User OAuth Token" (starts with xoxb-). Different from SLACK_CLIENT_SECRET.
SLACK_BOT_TOKEN = config("SLACK_BOT_TOKEN", default="")

# --- Microsoft Teams (Azure AD) OAuth ---
TEAMS_CLIENT_ID = config("TEAMS_CLIENT_ID", default="")
TEAMS_CLIENT_SECRET = config("TEAMS_CLIENT_SECRET", default="")
TEAMS_TENANT_ID = config("TEAMS_TENANT_ID", default="common")
TEAMS_REDIRECT_URI = config(
    "TEAMS_REDIRECT_URI", default=f"{BACKEND_URL}/api/auth/teams/callback/"
)
TEAMS_SCOPES = config("TEAMS_SCOPES", default="openid email profile User.Read")

# --- MongoDB (used directly via mongoengine for app data: users, oauth accounts) ---
MONGO_HOST = config("MONGO_HOST", default="mongodb://localhost:27017")
MONGO_DB_NAME = config("MONGO_DB_NAME", default="tmb_backend")

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
    ),
}

# Connect mongoengine to MongoDB. Django's own sqlite DB above still handles
# admin/sessions/auth tables; our app data (users, slack/teams accounts) lives
# in Mongo via the models in accounts/models.py.
import mongoengine  # noqa: E402

mongoengine.connect(db=MONGO_DB_NAME, host=MONGO_HOST)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
